components/utils/adder.v
components/alu.v
components/decoders/aludec.v
components/controller.v
components/datapath.v
components/memories/dmem.v
components/utils/extend.v
components/utils/flopenr.v
components/hazard_unit.v
components/memories/imem.v
components/decoders/maindec.v
components/utils/mux2.v
components/utils/mux3.v
components/registers/reg_ex_mem.v
components/registers/reg_id_ex.v
components/registers/reg_if_id.v
components/registers/reg_mem_wb.v
components/regfile.v
components/riscvpipeline.v
components/top.v